### ISSUE TITLE
Finalproject help

### ISSUE THREAD

**Issue by Avetch** [Avetch/markuplanguages-public#1]
Hi, when I try to apply the "a:hover" to the logo and the text which are on the top of the header it is just applied to the underline which is attached to them and not to the whole text and logo. It seems to happen because of the "span" tag that I used on the text in order to turn it blue, but I'm not sure. The files are in "Projects" folder" named as "FinalProject.html" and "FinalProjectCSS.css". Thank you for your help.

**Comment by zmwebdev** [comment]
The solution:

HTML:
```html
      <div id=Icons>
          <a href="Login.html"><span>Login here<i class="fa fa-user-circle-o" aria-hidden="true"></i></span></a><br>
          <a href="Register.html"><span>Are you new?<i class="fa fa-user-circle" aria-hidden="true"></i></span></a><br>
        </div>
```

CSS:
```css
/* unvisited link */
a:link {
    color: blue;
}

/* visited link */
a:visited {
    color: blue;
}

/* mouse over link */
a:hover {
    color:yellow;
}

/* selected link */
a:active {
    color: blue;
}
```

https://www.w3schools.com/css/css_link.asp

@Avetch
